"""Document Generator Tool — Convert Markdown to PDF, DOCX, CSV, or Excel.

The "Any Format" skill: takes Markdown text and converts it into professional
document formats for download or Slack file uploads.

Supported output formats:
    - PDF  (via reportlab)
    - DOCX (via python-docx)
    - CSV  (via pandas)
    - XLSX (via pandas + openpyxl)

MCP Pattern:
    - Typed inputs/outputs
    - Built-in error boundary
    - Returns file path + metadata for downstream upload

Zero-Token Fail-Safe:
    If a required library is missing, returns a structured error
    with the pip install command. Core NEXUS is never affected.
"""

import logging
import os
import re
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Optional

from mission_control import mission_control

logger = logging.getLogger("nexus.tools.document_generator")

# ── Output directory ─────────────────────────────────────
DATA_DIR = Path(__file__).parent.parent / "data" / "exports"
DATA_DIR.mkdir(parents=True, exist_ok=True)


# ── Helpers ──────────────────────────────────────────────

def _sanitize_filename(name: str) -> str:
    """Clean a string for safe use as a filename."""
    name = re.sub(r'[^\w\s-]', '', name).strip()
    name = re.sub(r'\s+', '_', name)
    return name[:80] or "nexus_document"


def _extract_table_from_markdown(text: str) -> tuple[list[str], list[list[str]]]:
    """Extract the first Markdown table as (headers, rows).

    Returns empty lists if no table found.
    """
    lines = text.strip().split('\n')
    table_start = None
    for i, line in enumerate(lines):
        if '|' in line and line.strip().startswith('|'):
            table_start = i
            break
    if table_start is None:
        return [], []

    # Header row
    header_line = lines[table_start]
    headers = [c.strip() for c in header_line.split('|') if c.strip()]

    # Skip separator row (|---|---|)
    data_start = table_start + 1
    if data_start < len(lines) and re.match(r'^[\s|:-]+$', lines[data_start]):
        data_start += 1

    # Data rows
    rows = []
    for line in lines[data_start:]:
        if '|' not in line or not line.strip().startswith('|'):
            break
        cells = [c.strip() for c in line.split('|') if c.strip()]
        rows.append(cells)

    return headers, rows


def _strip_markdown(text: str) -> str:
    """Convert markdown to plain text for PDF paragraphs."""
    text = re.sub(r'^#{1,6}\s+', '', text, flags=re.MULTILINE)  # headers
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'\1', text)  # bold+italic
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)  # bold
    text = re.sub(r'\*(.+?)\*', r'\1', text)  # italic
    text = re.sub(r'`([^`]+)`', r'\1', text)  # inline code
    text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)  # links
    text = re.sub(r'^[-*+]\s+', '• ', text, flags=re.MULTILINE)  # bullets
    text = re.sub(r'^>\s+', '', text, flags=re.MULTILINE)  # blockquotes
    return text


# ── Generators ───────────────────────────────────────────

def _generate_pdf(content: str, title: str, filepath: str) -> str:
    """Generate a PDF file from Markdown content using reportlab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        HRFlowable,
    )

    doc = SimpleDocTemplate(
        filepath, pagesize=A4,
        leftMargin=25*mm, rightMargin=25*mm,
        topMargin=20*mm, bottomMargin=20*mm,
    )
    styles = getSampleStyleSheet()

    # Custom styles
    styles.add(ParagraphStyle(
        'NexusTitle', parent=styles['Title'],
        fontSize=18, spaceAfter=6, textColor=HexColor('#1e293b'),
    ))
    styles.add(ParagraphStyle(
        'NexusMeta', parent=styles['Normal'],
        fontSize=9, textColor=HexColor('#64748b'), spaceAfter=12,
    ))
    styles.add(ParagraphStyle(
        'NexusBody', parent=styles['Normal'],
        fontSize=11, leading=16, spaceAfter=8, textColor=HexColor('#334155'),
    ))
    styles.add(ParagraphStyle(
        'NexusH2', parent=styles['Heading2'],
        fontSize=14, spaceBefore=14, spaceAfter=6, textColor=HexColor('#1e293b'),
    ))

    story = []

    # Title + metadata
    story.append(Paragraph(title, styles['NexusTitle']))
    story.append(Paragraph(
        f"Generated by NEXUS · {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        styles['NexusMeta'],
    ))
    story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor('#e2e8f0')))
    story.append(Spacer(1, 8))

    # Process content line by line
    plain = _strip_markdown(content)
    for line in plain.split('\n'):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 4))
        elif line.startswith('• '):
            story.append(Paragraph(f"&bull; {line[2:]}", styles['NexusBody']))
        else:
            story.append(Paragraph(line, styles['NexusBody']))

    # If there's a table, render it
    headers, rows = _extract_table_from_markdown(content)
    if headers and rows:
        story.append(Spacer(1, 10))
        table_data = [headers] + rows
        t = Table(table_data, repeatRows=1)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), HexColor('#f1f5f9')),
            ('TEXTCOLOR', (0, 0), (-1, 0), HexColor('#1e293b')),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#cbd5e1')),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(t)

    # Footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.3, color=HexColor('#e2e8f0')))
    story.append(Paragraph("NEXUS Autonomous Life OS", styles['NexusMeta']))

    doc.build(story)
    return filepath


def _generate_docx(content: str, title: str, filepath: str) -> str:
    """Generate a DOCX file from Markdown content using python-docx."""
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Title
    title_para = doc.add_heading(title, level=0)
    for run in title_para.runs:
        run.font.color.rgb = RGBColor(0x1e, 0x29, 0x3b)

    # Metadata
    meta = doc.add_paragraph()
    meta_run = meta.add_run(f"Generated by NEXUS · {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = RGBColor(0x64, 0x74, 0x8b)

    # Content
    lines = content.split('\n')
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue

        # Headers
        h_match = re.match(r'^(#{1,4})\s+(.+)', stripped)
        if h_match:
            level = len(h_match.group(1))
            doc.add_heading(h_match.group(2), level=min(level, 4))
            continue

        # Bullet lists
        if re.match(r'^[-*+]\s+', stripped):
            item_text = re.sub(r'^[-*+]\s+', '', stripped)
            doc.add_paragraph(item_text, style='List Bullet')
            continue

        # Numbered lists
        ol_match = re.match(r'^\d+\.\s+(.+)', stripped)
        if ol_match:
            doc.add_paragraph(ol_match.group(1), style='List Number')
            continue

        # Blockquotes
        if stripped.startswith('>'):
            quote_text = stripped.lstrip('> ')
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.5)
            run = p.add_run(quote_text)
            run.font.italic = True
            run.font.color.rgb = RGBColor(0x64, 0x74, 0x8b)
            continue

        # Regular paragraph (strip inline markdown)
        clean = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped)
        clean = re.sub(r'\*(.+?)\*', r'\1', clean)
        clean = re.sub(r'`([^`]+)`', r'\1', clean)
        clean = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', clean)
        doc.add_paragraph(clean)

    # Table if present
    headers, rows = _extract_table_from_markdown(content)
    if headers and rows:
        table = doc.add_table(rows=1 + len(rows), cols=len(headers))
        table.style = 'Light Grid Accent 1'
        for i, h in enumerate(headers):
            table.rows[0].cells[i].text = h
        for ri, row in enumerate(rows):
            for ci, cell in enumerate(row):
                if ci < len(headers):
                    table.rows[ri + 1].cells[ci].text = cell

    doc.save(filepath)
    return filepath


def _generate_csv(content: str, title: str, filepath: str) -> str:
    """Generate a CSV file from Markdown table data."""
    import pandas as pd

    headers, rows = _extract_table_from_markdown(content)
    if not headers or not rows:
        # Fallback: line-per-row with single "Content" column
        lines = [l.strip() for l in content.split('\n') if l.strip()]
        df = pd.DataFrame({"Content": lines})
    else:
        # Pad rows to match header length
        padded = [r + [''] * (len(headers) - len(r)) for r in rows]
        df = pd.DataFrame(padded, columns=headers)

    df.to_csv(filepath, index=False)
    return filepath


def _generate_xlsx(content: str, title: str, filepath: str) -> str:
    """Generate an Excel file from Markdown table data."""
    import pandas as pd

    headers, rows = _extract_table_from_markdown(content)
    if not headers or not rows:
        lines = [l.strip() for l in content.split('\n') if l.strip()]
        df = pd.DataFrame({"Content": lines})
    else:
        padded = [r + [''] * (len(headers) - len(r)) for r in rows]
        df = pd.DataFrame(padded, columns=headers)

    df.to_excel(filepath, index=False, sheet_name=title[:31] or "Sheet1")
    return filepath


# ── Core Tool Function ───────────────────────────────────

GENERATORS = {
    "pdf":  (".pdf",  _generate_pdf),
    "docx": (".docx", _generate_docx),
    "csv":  (".csv",  _generate_csv),
    "xlsx": (".xlsx", _generate_xlsx),
    "excel": (".xlsx", _generate_xlsx),  # alias
}


async def generate_document(
    run_id: str,
    agent_name: str,
    content: str,
    format: str = "pdf",
    title: str = "NEXUS Document",
) -> dict:
    """Convert Markdown content into a downloadable document file.

    Args:
        run_id: Current agent run ID
        agent_name: Calling agent name
        content: Markdown text to convert
        format: Output format — "pdf", "docx", "csv", or "xlsx"
        title: Document title

    Returns:
        dict with: status, file_path, format, size_bytes, filename
    """
    await mission_control.emit_tool_call(
        run_id, agent_name, "document.generate",
        {"format": format, "title": title, "content_length": len(content)}
    )

    fmt = format.lower().strip()
    if fmt not in GENERATORS:
        return {
            "status": "error",
            "message": f"Unsupported format '{format}'. Use: pdf, docx, csv, xlsx.",
        }

    ext, generator = GENERATORS[fmt]
    safe_name = _sanitize_filename(title)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{safe_name}_{timestamp}{ext}"
    filepath = str(DATA_DIR / filename)

    try:
        await mission_control.emit_narration(
            run_id, agent_name,
            f"Generating {fmt.upper()} document: {title}..."
        )

        generator(content, title, filepath)

        size = os.path.getsize(filepath)

        await mission_control.emit_tool_result(
            run_id, agent_name, "document.generate",
            {"format": fmt, "filename": filename, "size_bytes": size}
        )

        logger.info(f"Document generated: {filename} ({size:,} bytes)")
        return {
            "status": "ok",
            "file_path": filepath,
            "filename": filename,
            "format": fmt,
            "size_bytes": size,
            "download_url": f"/data/exports/{filename}",
            "message": f"✅ {fmt.upper()} document generated: **{filename}** ({size:,} bytes)",
        }

    except ImportError as e:
        lib = str(e).split("'")[-2] if "'" in str(e) else str(e)
        logger.error(f"Document generation failed — missing library: {lib}")
        return {
            "status": "error",
            "message": f"Missing library for {fmt.upper()} generation. Run: pip install {lib}",
        }

    except Exception as e:
        logger.error(f"Document generation failed: {e}")
        return {
            "status": "error",
            "message": f"Failed to generate {fmt.upper()}: {str(e)[:200]}",
        }


def get_status() -> dict:
    """Get document generator tool status."""
    available_formats = []
    try:
        import reportlab  # noqa: F401
        available_formats.append("PDF")
    except ImportError:
        pass
    try:
        import docx  # noqa: F401
        available_formats.append("DOCX")
    except ImportError:
        pass
    try:
        import pandas  # noqa: F401
        available_formats.extend(["CSV", "XLSX"])
    except ImportError:
        pass
    return {
        "name": "Document Generator",
        "enabled": len(available_formats) > 0,
        "formats": available_formats,
    }
